In [1]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
Yes, there is a difference in the data type of variables list_ and array_list

In [2]:
list_

['1', '2', '3', '4', '5']

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
data_type_list_ = type(list_)

In [5]:
data_type_list_

list

In [6]:
data_type_array_list = type(array_list)

In [7]:
data_type_array_list

numpy.ndarray

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [8]:
list_

['1', '2', '3', '4', '5']

In [9]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [14]:
data_type_list_ = type(list_)

In [10]:
data_type_list_ 

list

In [11]:
data_type_array_list = type(array_list)

In [12]:
data_type_array_list

numpy.ndarray

In [13]:
type(list_[0])

str

In [50]:
for element in list_:
    element_data_type = type(element)
    print(f"Data type of element{element_data_type}")

Data type of element<class 'str'>
Data type of element<class 'str'>
Data type of element<class 'str'>
Data type of element<class 'str'>
Data type of element<class 'str'>


In [25]:
for element in array_list:
    element_data_type = type(element)
    print(f"Data type of element{element_data_type}")

Data type of element<class 'numpy.str_'>
Data type of element<class 'numpy.str_'>
Data type of element<class 'numpy.str_'>
Data type of element<class 'numpy.str_'>
Data type of element<class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [25]:
array_list = np.array(object = list_, dtype = int)

In [26]:
array_list 

array([1, 2, 3, 4, 5])

In [20]:
list_

['1', '2', '3', '4', '5']

In [21]:
data_type_list_ = type(list_)

In [22]:
data_type_list_

list

In [27]:
data_type_array_list = type(array_list)

In [28]:
data_type_array_list

numpy.ndarray

In [ ]:
yes,there is a differnce in the data type of elements present in the variables list_ and array_list

In [29]:
for element in list_:
    element_data_type = type(element)
    print("Data type of element{element}".format(element = element_data_type))

Data type of element<class 'str'>
Data type of element<class 'str'>
Data type of element<class 'str'>
Data type of element<class 'str'>
Data type of element<class 'str'>


In [30]:
for element in array_list:
    element_data_type = type(element)
    print(f"Data type of element{element_data_type}")

Data type of element<class 'numpy.int64'>
Data type of element<class 'numpy.int64'>
Data type of element<class 'numpy.int64'>
Data type of element<class 'numpy.int64'>
Data type of element<class 'numpy.int64'>


In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [31]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [32]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [33]:
num_array = np.array(object = num_list)


In [34]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
num_array.shape

(2, 3)

In [36]:
num_array.size

6

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [38]:
import  numpy as np
num_array = np.zeros((3,3))

In [39]:
num_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
num_array.shape

(3, 3)

In [41]:
num_array.size

9

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [43]:
identity_matrix = np.eye(5)

In [44]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
identity_matrix.shape

(5, 5)

In [47]:
identity_matrix.size

25